//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18052.
// 
#pragma warning disable 1591

namespace ApptBookingTestConsole.KSOSC {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SE3ControllingService1Soap", Namespace="http://www.kingfisher.co.uk/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ErrorForSE3))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CancelAppointmentStatusForSE3))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AppointmentForSE3))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReturnAvailabilityToSE3[]))]
    public partial class SE3ControllingService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAvailabilityOperationCompleted;
        
        private System.Threading.SendOrPostCallback BookAppointmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelAppointmentOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SE3ControllingService1() {
            this.Url = global::ApptBookingTestConsole.Properties.Settings.Default.ApptBookingTestConsole_KSOSC1_SE3ControllingService1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAvailabilityCompletedEventHandler GetAvailabilityCompleted;
        
        /// <remarks/>
        public event BookAppointmentCompletedEventHandler BookAppointmentCompleted;
        
        /// <remarks/>
        public event CancelAppointmentCompletedEventHandler CancelAppointmentCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kingfisher.co.uk/GetAvailability", RequestNamespace="http://www.kingfisher.co.uk/", ResponseNamespace="http://www.kingfisher.co.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object GetAvailability(InputFromSE3ForFindAvailability inputFromSE3ForAvailability) {
            object[] results = this.Invoke("GetAvailability", new object[] {
                        inputFromSE3ForAvailability});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void GetAvailabilityAsync(InputFromSE3ForFindAvailability inputFromSE3ForAvailability) {
            this.GetAvailabilityAsync(inputFromSE3ForAvailability, null);
        }
        
        /// <remarks/>
        public void GetAvailabilityAsync(InputFromSE3ForFindAvailability inputFromSE3ForAvailability, object userState) {
            if ((this.GetAvailabilityOperationCompleted == null)) {
                this.GetAvailabilityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAvailabilityOperationCompleted);
            }
            this.InvokeAsync("GetAvailability", new object[] {
                        inputFromSE3ForAvailability}, this.GetAvailabilityOperationCompleted, userState);
        }
        
        private void OnGetAvailabilityOperationCompleted(object arg) {
            if ((this.GetAvailabilityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAvailabilityCompleted(this, new GetAvailabilityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kingfisher.co.uk/BookAppointment", RequestNamespace="http://www.kingfisher.co.uk/", ResponseNamespace="http://www.kingfisher.co.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object BookAppointment(InputFromSE3ForBookAppointment inputFromSE3ForBookAppointment) {
            object[] results = this.Invoke("BookAppointment", new object[] {
                        inputFromSE3ForBookAppointment});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void BookAppointmentAsync(InputFromSE3ForBookAppointment inputFromSE3ForBookAppointment) {
            this.BookAppointmentAsync(inputFromSE3ForBookAppointment, null);
        }
        
        /// <remarks/>
        public void BookAppointmentAsync(InputFromSE3ForBookAppointment inputFromSE3ForBookAppointment, object userState) {
            if ((this.BookAppointmentOperationCompleted == null)) {
                this.BookAppointmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBookAppointmentOperationCompleted);
            }
            this.InvokeAsync("BookAppointment", new object[] {
                        inputFromSE3ForBookAppointment}, this.BookAppointmentOperationCompleted, userState);
        }
        
        private void OnBookAppointmentOperationCompleted(object arg) {
            if ((this.BookAppointmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BookAppointmentCompleted(this, new BookAppointmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kingfisher.co.uk/CancelAppointment", RequestNamespace="http://www.kingfisher.co.uk/", ResponseNamespace="http://www.kingfisher.co.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object CancelAppointment(InputFromSE3ForCancelAppointment inputFromSE3ForCancelAppointment) {
            object[] results = this.Invoke("CancelAppointment", new object[] {
                        inputFromSE3ForCancelAppointment});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void CancelAppointmentAsync(InputFromSE3ForCancelAppointment inputFromSE3ForCancelAppointment) {
            this.CancelAppointmentAsync(inputFromSE3ForCancelAppointment, null);
        }
        
        /// <remarks/>
        public void CancelAppointmentAsync(InputFromSE3ForCancelAppointment inputFromSE3ForCancelAppointment, object userState) {
            if ((this.CancelAppointmentOperationCompleted == null)) {
                this.CancelAppointmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelAppointmentOperationCompleted);
            }
            this.InvokeAsync("CancelAppointment", new object[] {
                        inputFromSE3ForCancelAppointment}, this.CancelAppointmentOperationCompleted, userState);
        }
        
        private void OnCancelAppointmentOperationCompleted(object arg) {
            if ((this.CancelAppointmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelAppointmentCompleted(this, new CancelAppointmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kingfisher.co.uk/")]
    public partial class InputFromSE3ForFindAvailability {
        
        private System.DateTime dateFromField;
        
        private System.DateTime dateToField;
        
        private string appointmentLocationField;
        
        private string storeIDField;
        
        private string[] consultantListsField;
        
        /// <remarks/>
        public System.DateTime dateFrom {
            get {
                return this.dateFromField;
            }
            set {
                this.dateFromField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dateTo {
            get {
                return this.dateToField;
            }
            set {
                this.dateToField = value;
            }
        }
        
        /// <remarks/>
        public string AppointmentLocation {
            get {
                return this.appointmentLocationField;
            }
            set {
                this.appointmentLocationField = value;
            }
        }
        
        /// <remarks/>
        public string StoreID {
            get {
                return this.storeIDField;
            }
            set {
                this.storeIDField = value;
            }
        }
        
        /// <remarks/>
        public string[] ConsultantLists {
            get {
                return this.consultantListsField;
            }
            set {
                this.consultantListsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kingfisher.co.uk/")]
    public partial class InputFromSE3ForCancelAppointment {
        
        private string exchangeIDField;
        
        private string consultantIDField;
        
        /// <remarks/>
        public string exchangeID {
            get {
                return this.exchangeIDField;
            }
            set {
                this.exchangeIDField = value;
            }
        }
        
        /// <remarks/>
        public string consultantID {
            get {
                return this.consultantIDField;
            }
            set {
                this.consultantIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kingfisher.co.uk/")]
    public partial class InputFromSE3ForBookAppointment {
        
        private string consultantIDField;
        
        private System.DateTime dateFromField;
        
        private System.DateTime dateToField;
        
        private decimal timeFromField;
        
        private decimal timeToField;
        
        private string notesField;
        
        private string appointmentLocationField;
        
        private string storeIDField;
        
        private string appointmentAttachmentField;
        
        /// <remarks/>
        public string consultantID {
            get {
                return this.consultantIDField;
            }
            set {
                this.consultantIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dateFrom {
            get {
                return this.dateFromField;
            }
            set {
                this.dateFromField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dateTo {
            get {
                return this.dateToField;
            }
            set {
                this.dateToField = value;
            }
        }
        
        /// <remarks/>
        public decimal timeFrom {
            get {
                return this.timeFromField;
            }
            set {
                this.timeFromField = value;
            }
        }
        
        /// <remarks/>
        public decimal timeTo {
            get {
                return this.timeToField;
            }
            set {
                this.timeToField = value;
            }
        }
        
        /// <remarks/>
        public string notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        public string appointmentLocation {
            get {
                return this.appointmentLocationField;
            }
            set {
                this.appointmentLocationField = value;
            }
        }
        
        /// <remarks/>
        public string storeID {
            get {
                return this.storeIDField;
            }
            set {
                this.storeIDField = value;
            }
        }
        
        /// <remarks/>
        public string AppointmentAttachment {
            get {
                return this.appointmentAttachmentField;
            }
            set {
                this.appointmentAttachmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kingfisher.co.uk/")]
    public partial class ReturnAvailabilityToSE3 {
        
        private string consultantIDField;
        
        private string consultantNameField;
        
        private string dateFromField;
        
        private decimal timeFromField;
        
        private string dateToField;
        
        private decimal timeToField;
        
        private string availabilityStatusField;
        
        /// <remarks/>
        public string ConsultantID {
            get {
                return this.consultantIDField;
            }
            set {
                this.consultantIDField = value;
            }
        }
        
        /// <remarks/>
        public string ConsultantName {
            get {
                return this.consultantNameField;
            }
            set {
                this.consultantNameField = value;
            }
        }
        
        /// <remarks/>
        public string DateFrom {
            get {
                return this.dateFromField;
            }
            set {
                this.dateFromField = value;
            }
        }
        
        /// <remarks/>
        public decimal TimeFrom {
            get {
                return this.timeFromField;
            }
            set {
                this.timeFromField = value;
            }
        }
        
        /// <remarks/>
        public string DateTo {
            get {
                return this.dateToField;
            }
            set {
                this.dateToField = value;
            }
        }
        
        /// <remarks/>
        public decimal TimeTo {
            get {
                return this.timeToField;
            }
            set {
                this.timeToField = value;
            }
        }
        
        /// <remarks/>
        public string AvailabilityStatus {
            get {
                return this.availabilityStatusField;
            }
            set {
                this.availabilityStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kingfisher.co.uk/")]
    public partial class ErrorForSE3 {
        
        private System.DateTime creationDateField;
        
        private HttpStatusCode serviceResponseErrorCodeField;
        
        private string serviceResponseErrorTextField;
        
        /// <remarks/>
        public System.DateTime CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
            }
        }
        
        /// <remarks/>
        public HttpStatusCode ServiceResponseErrorCode {
            get {
                return this.serviceResponseErrorCodeField;
            }
            set {
                this.serviceResponseErrorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceResponseErrorText {
            get {
                return this.serviceResponseErrorTextField;
            }
            set {
                this.serviceResponseErrorTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kingfisher.co.uk/")]
    public enum HttpStatusCode {
        
        /// <remarks/>
        Continue,
        
        /// <remarks/>
        SwitchingProtocols,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        Created,
        
        /// <remarks/>
        Accepted,
        
        /// <remarks/>
        NonAuthoritativeInformation,
        
        /// <remarks/>
        NoContent,
        
        /// <remarks/>
        ResetContent,
        
        /// <remarks/>
        PartialContent,
        
        /// <remarks/>
        MultipleChoices,
        
        /// <remarks/>
        Ambiguous,
        
        /// <remarks/>
        MovedPermanently,
        
        /// <remarks/>
        Moved,
        
        /// <remarks/>
        Found,
        
        /// <remarks/>
        Redirect,
        
        /// <remarks/>
        SeeOther,
        
        /// <remarks/>
        RedirectMethod,
        
        /// <remarks/>
        NotModified,
        
        /// <remarks/>
        UseProxy,
        
        /// <remarks/>
        Unused,
        
        /// <remarks/>
        TemporaryRedirect,
        
        /// <remarks/>
        RedirectKeepVerb,
        
        /// <remarks/>
        BadRequest,
        
        /// <remarks/>
        Unauthorized,
        
        /// <remarks/>
        PaymentRequired,
        
        /// <remarks/>
        Forbidden,
        
        /// <remarks/>
        NotFound,
        
        /// <remarks/>
        MethodNotAllowed,
        
        /// <remarks/>
        NotAcceptable,
        
        /// <remarks/>
        ProxyAuthenticationRequired,
        
        /// <remarks/>
        RequestTimeout,
        
        /// <remarks/>
        Conflict,
        
        /// <remarks/>
        Gone,
        
        /// <remarks/>
        LengthRequired,
        
        /// <remarks/>
        PreconditionFailed,
        
        /// <remarks/>
        RequestEntityTooLarge,
        
        /// <remarks/>
        RequestUriTooLong,
        
        /// <remarks/>
        UnsupportedMediaType,
        
        /// <remarks/>
        RequestedRangeNotSatisfiable,
        
        /// <remarks/>
        ExpectationFailed,
        
        /// <remarks/>
        UpgradeRequired,
        
        /// <remarks/>
        InternalServerError,
        
        /// <remarks/>
        NotImplemented,
        
        /// <remarks/>
        BadGateway,
        
        /// <remarks/>
        ServiceUnavailable,
        
        /// <remarks/>
        GatewayTimeout,
        
        /// <remarks/>
        HttpVersionNotSupported,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kingfisher.co.uk/")]
    public partial class ResponseStatusForSE3 {
        
        private HttpStatusCode serviceResponseStatusCodeField;
        
        private string serviceResponseStatusTextField;
        
        /// <remarks/>
        public HttpStatusCode ServiceResponseStatusCode {
            get {
                return this.serviceResponseStatusCodeField;
            }
            set {
                this.serviceResponseStatusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceResponseStatusText {
            get {
                return this.serviceResponseStatusTextField;
            }
            set {
                this.serviceResponseStatusTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kingfisher.co.uk/")]
    public partial class CancelAppointmentStatusForSE3 {
        
        private ResponseStatusForSE3 serviceResponseField;
        
        /// <remarks/>
        public ResponseStatusForSE3 ServiceResponse {
            get {
                return this.serviceResponseField;
            }
            set {
                this.serviceResponseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kingfisher.co.uk/")]
    public partial class AppointmentForSE3 {
        
        private string exchangeIDField;
        
        /// <remarks/>
        public string ExchangeID {
            get {
                return this.exchangeIDField;
            }
            set {
                this.exchangeIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAvailabilityCompletedEventHandler(object sender, GetAvailabilityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAvailabilityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAvailabilityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void BookAppointmentCompletedEventHandler(object sender, BookAppointmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BookAppointmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BookAppointmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CancelAppointmentCompletedEventHandler(object sender, CancelAppointmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelAppointmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelAppointmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591